def modules = []
modules = env.Module.toString().split(",")
def runAll = "".equals(modules[0])
def gitBranch = env.BRANCH_NAME

pipeline {
    agent {
        node {
            label 'master'
        }
    }

    tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }

    stages {
        
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }


        stage('SCM') {
            steps {
                script {
                    if (null == gitBranch || "".equals(gitBranch)) {
                        gitBranch = scm.branches[0].name
                    }

                    gitBranch = gitBranch.replace("*/", "").replace("refs/heads/","")
                }

                git url: 'https://github.com/rodrigorodes/ci.git', branch: "$gitBranch"
            }
        }

        stage('Build Project') {
            steps {
                script {
                    dir (env.WORKSPACE) {
                        sh 'mvn clean install'
                   }
                }
            }

            post {
                success {
                  archiveArtifacts artifacts: "**/target/*", fingerprint: true
                }
            }
        }
    }
}
